//
//  Product.swift
//  EL Nutritious
//
//  Created by Pari Gulati on 7/12/23.
//

import Foundation

struct Product: Identifiable {
    var id = UUID()
    var line: String
    var name: String
    var sub: String
    var quantity: String
    var image: String
    var price: Int
    var rating: Double
    var description: String
    var skinType: String
}

var productList = [Product(line: "Nutritious", name: "2-in-1 Foam Cleanser", sub: "Purify. Pores. Glow.", quantity: "4.2", image: "CleanserShop", price: 27, rating: 4.3, description: "Show your skin some love with peak performance skincare from NUTRITIOUS. If your skin is grumpy, dull and irritable, this collection is what you need. Ingeniously calibrated, nutrient-rich formulas feature naturally derived ingredients. Skincare that will help skin flourish and flaunt its natural vibrancy. It’s as simple as that 2-in-1 Foam Cleanser works as a daily cleanser or weekly purifying mask. Cleanses + Deeply Purifies. Kicks off regimen. Healthier-looking. Blissful-feeling. Vitality-loving skin. Proof positive. After just 1 application: Pores appear minimized: -17%* 96% said it removed excess oil** 97% naturally derived formula.*** Infused with our Nutri-9 Complex, which includes: Sweet Kelp (responsibly sourced) Red Algae Ferment (responsibly sourced) Coconut Water Ferment (our proprietary ferment Skin-loving, future loving. Our commitment to a more beautiful future. Designed with packaging sustainability. The packaging for this product contains at least 27% post-consumer recycled content. Learn more about our Sustainability practices. EWG Verified®: Our Nutritious collection is EWG VERIFIED® by Environmental Working Group (EWG), a third-party non-profit organization. This verification means that our formulas meet some of the strictest formulation standards, transparency requirements, and we use good manufacturing processe *Clinical testing on 33 women. **Consumer testing on 103 women. ***Per ISO Standard 16128. From plant sources, non-petroleum mineral sources, and/or water.)", skinType: "Normal/Combo/Oily"),
                   Product(line: "Nutritious", name: "Radiant Essence Treatment Lotion", sub: "Prep. Infuse. Glow.", quantity: "6.7", image: "LotionShop", price: 42, rating: 3.0, description: "Show your skin some love with peak performance skincare from NUTRITIOUS. If your skin is grumpy, dull and irritable, this collection is what you need. Ingeniously calibrated, nutrient-rich formulas feature naturally derived ingredients. Skincare that will help skin flourish and flaunt its natural vibrancy. It’s as simple as that. Radiant Essence Lotion delivers a cushioning, hydrating infusion. Awakens. Balances. Calms. Preps for regimen. Healthier-looking. Blissful-feeling. Vitality-loving skin. Proof positive. Oiliness looks reduced: -40%* Pores look minimized: -31%* And it helps prevent redness with one application** 95% naturally derived formula.*** Infused with our Nutri-9 Complex, which includes: Sweet Kelp to help fight oiliness and minimize the appearance of pores (responsibly sourced) Red Algae Ferment to soothe and reduce visible redness (responsibly sourced) Coconut Water Ferment to hydrate and nourish (our proprietary ferment) Skin-loving, future loving. Our commitment to a more beautiful future. Recyclable carton from FSC-certified paper. Designed with packaging sustainability. Please recycle the bottle. Learn more about our Sustainability practices.EWG Verified®: Our Nutritious collection is EWG VERIFIED® by Environmental Working Group (EWG), a third-party non-profit organization. This verification means that our formulas meet some of the strictest formulation standards, transparency requirements, and we use good manufacturing processes. *Clinical testing on 32 women, after using product for 8 weeks. **After pre-treatment period; clinical testing on 29 people measured for 2.5 hours, versus untreated control. ***Per ISO Standard 16128. From plant sources, non-petroleum mineral sources, and/or water.", skinType: "Normal/Combo/Oily"),
                   Product(line: "Nutritious", name: "Melting Soft Creme/Mask Moisturizer", sub: "Pores. Hydration. Glow.", quantity: "1.7", image: "CreamShop", price: 48, rating: 4.5, description: "Show your skin some love with peak performance skincare from NUTRITIOUS. If your skin is grumpy, dull and irritable, this collection is what you need. Ingeniously calibrated, nutrient-rich formulas feature naturally derived ingredients. Skincare that will help skin flourish and flaunt its natural vibrancy. It’s as simple as that. Melting Soft Creme/Mask melts into skin. Comfortable, cushy, pillowy feel. Calms. Renews. Strengthens. Quenching, soothing hydration. Skin thrives with now-awakened vitality. Proof positive. Boosts moisture after one application Skin barrier is strengthened with one application Oiliness looks reduced: -52%* Pores look minimized: -41%* 93% naturally derived formula.** Infused with our Nutri-9 Complex, which includes: Sweet Kelp to help fight oiliness and minimize the appearance of pores (responsibly sourced) Red Algae Ferment to soothe and reduce visible redness (responsibly sourced) Coconut Water Ferment to hydrate and nourish (our proprietary ferment) Skin-loving, future loving. Our commitment to a more beautiful future. Recyclable carton from FSC-certified paper. Designed with packaging sustainability. Please recycle. Learn more about our Sustainability practices. EWG Verified®: Our Nutritious collection is EWG VERIFIED® by Environmental Working Group (EWG), a third-party non-profit organization. This verification means that our formulas meet some of the strictest formulation standards, transparency requirements, and we use good manufacturing processes.*Clinical testing on 29 women after using product for 8 weeks. **Per ISO Standard 16128. From plant sources, non-petroleum mineral sources, and/or water.", skinType: "Normal/Combo/Oily")]
